config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories
  resources :items
  resources :users
  resources :orders
  root 'categories#index'
  # root 'mst_items#index'
end

# Rails.application.routes.draw do

#   get 'order_detail/resources'
#   resources :categories do
#     collection do
#       get 'search'
#       post 'search'
#     end
#   end

#   resources :items do
#     collection do
#       get 'search'
#       post 'search'
#     end
#   end

#   resources :users do
#   collection do
#     get 'search'
#     post 'search'
#   end
# end
#   resources :orders
#   resources :order_details
#   root 'categories#index'
# end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true, length: { minimum: 1, message: 'Too short to name' }
  validates :code, presence:true,uniqueness: true

  def self.search(search)
    if search
     Category.where(['name Like ?',"%#{search}%"])
    else
     Category.all
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  validates :name, presence: true, length: { minimum: 1, message: 'Too short to name' }
  # default_scope { order(created_at: :asc)}

  scope :search, ->(parameter) do
    result = Item
    parameters = parameter.split(/[[:blank:]]+/)
    parameters.each do |search|
      result = result.where(['name Like ? or note Like ?',"%#{search}%","%#{search}%"])
    end
    result
  end
end


# def self.search(search)
#   if search
#    Category.where(['name Like ?',"%#{search}%"])
#   else
#    Category.all
#   end
# end
# end

#keywordおろしてきて
#words = keyword.split('')
#words.each do |word|



# scope :search, ->(parameter) do
#   result = Item
#   parameters = parameter.split(/[[:blank:]]+/)
#   parameters.each do |search|
#     result = result.where(['name Like ? or note Like ?',"%#{search}%","%#{search}%"])
#   end
#   result
# end

# def search
#   search_keywords = params[:search].to_s.split(/[[:blank:]]+/)
#   category_id = params[:category]
#   search_query = create_search_query(search_keywords, category_id)
#   @items = Item.where(search_query)
# end

app/models/order.rb
class Order < ApplicationRecord
  has_many :orderdetails,dependent: :destory
  belongs_to :user
  has_many :items through: :orderdetails
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :Order
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  has_many :Orders
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name,presence: true,uniqueness: true
  validates :tel,presence: true,uniqueness: true,length: { maximum: 11 }
  validates :email,presence: true,uniqueness: true,length: { maximum: 100 },
            format: { with: VALID_EMAIL_REGEX }
  def self.search(search)
    if search
     User.where(['name Like ?',"%#{search}%"])
    else
     User.all
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # Convention over Configuration (CoC)

  def index
    # @categories = Category.all.order(created_at: 'asc')
    @categories = Category.search(params[:search])
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    # render plain: params[:post].inspect
    # save
    # @post = Post.new(params[:post])
    # @post = Post.new(params.require(:post).permit(:title, :body))
    @category = Category.new(category_params)
    if @category.save
      # redirect
      redirect_to categories_path(@category)
    else
      # render plain: @post.errors.inspect
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end


  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private
    def category_params
      params.require(:category).permit(:name,:code)
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = params[:search] ? Item.search(params[:search]) : Item.all.order(created_at: "DESC")
    @items = @items.where(category: Category.find(params[:category])) if params[:category]
    # Item.all.order(created_at: "DESC")
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
    redirect_to item_path(@item)
    else
      render 'new'
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    # render plain: params[:item].inspect
    if    @item.update(item_params)
    redirect_to item_path
    else
      render 'edit'
    end
  end

 def destroy
    @item.destroy
    redirect_to items_path
  end

  private
    def item_params
      params.require(:item).permit(:name,:category_id,:code,:note,:price)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.search(params[:search])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
    redirect_to users_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    # render plain: params[:item].inspect
    if    @user.update(user_params)
    redirect_to user_path
    else
      render 'edit'
    end
  end

 def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:name,:code,:email)
    end
end

app/helpers/orderdetails_helper.rb
module OrderdetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
<p>
  <%= f.text_field :name, placeholder: '名前を入力してください' %>
  <% if @category.errors.messages[:name].any? %>
  <span class="error"><%= @category.errors.messages[:name][0] %></span>
  <% end %>
</p>
<p class="flex">
  <%= f.submit class: "btn btn-primary active" %>
</p>
<% end %>

app/views/categories/index.html.erb
<% provide(:title, "カテゴリ一覧") %>
<div class="main-table-front">
  <%= link_to image_tag('btn_kensyu.png', class: 'btn_Add'), new_category_path %>
  <div class="category_space"></div>
  <%= form_tag(categories_path,:method => 'get' ,class: "serchform") do %>
  <%= text_field_tag :search,params[:search],:placeholder => "カテゴリー入力" %>
  <%= submit_tag '検索', :name => nil ,class: "btn"%>
  <% end %>
</div>
<table border="1">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Edit</th>
      <th class="option_th">Delete</th>
      <th class="option_th">count</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= link_to category.name, category_path(category) %></td>
        <td><%= link_to '[Edit]', edit_category_path(category), class: 'command' %></td>
        <td><%= link_to '[x]',category_path(category),method: :delete,class: 'command',data: { confirm: 'Sure?' } %></td>
        <td><%= category.items.count %></td>
      </tr>
    <% end %>
  </tbody>
</tabel>

app/views/categories/new.html.erb
<% provide(:title, "カテゴリー作成") %>

<% provide(:title, "アイテム作成") %>
<%= form_for @category do |f| %>
 <% if @category.errors.any? %>
 <div id="error_explanation">
   <h2><%= pluralize(@category.errors.count, "error") %> エラーの為保存出来ません</h2>

   <ul>
   <% @category.errors.full_messages.each do |message| %>
     <li><%= message %></li>
   <% end %>
   </ul>
 </div>
 <% end %>

 <div class="form-group mt_50">
   <%= f.label :code %>
   <%= f.text_field :code,placeholder: "codeを入力して下さい", class: 'form-control' %>
 </div>

 <div class="form-group mt_50">
   <%= f.label :カテゴリー名 %>
   <%= f.text_field :name,placeholder: "商品名を入力して下さい", class: 'form-control' %>
 </div>

<div class="form flex">
 <%= f.submit class: "btn btn-primary active" %>
</div>
 <% end %>

app/views/categories/show.html.erb
<div class="show_container">
  <h2>Name: <%= @category.name %></h2>
  <h2>ID: <%= @category.id %></h2>
  <h2>Code: <%= @category.code %></h2>
</div>

app/views/items/edit.html.erb
<h2>Edit Item</h2>
<%= form_for @item, :url => {:action => :update} do |f| %>
<p>
  <%= f.text_field :name, placeholder: 'enter name' %>
</p>
<p>
  <%= f.text_field :code, placeholder: 'enter code' %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/items/index.html.erb
<% provide(:title, "アイテム一覧") %>
<div class="main-table-front">
      <%= link_to image_tag('btn_kensyu.png', class: 'btn_Add'), new_item_path %>
      <%= form_tag(items_path,:method => 'get' ,class: "serchform") do %>
  <%= select_tag :category, options_for_select(Category.all.map {|c| [c.name, c.id]}),:prompt => "すべて"%>

   <%= text_field_tag :search,params[:search],:placeholder => "アイテム入力" %>
 <%= submit_tag '検索', :name => nil ,class: "btn"%>
 <% end %>
</div>
<table border="1">
<thead>
<tr>
  <th>Code</th>
  <th>Name</th>
  <th class="category_th">category</th>
  <th class="category_th">price</th>
</tr>
</thead>
<tbody>
<% @items.each do |item| %>
<tr>
  <td><%= item.code %></td>
  <td><%= link_to item.name, item_path(item) %></td>
  <td><%= item.category.name %></td>
  <td><%= item.price %></td>
</tr>
<% end %>
</tbody>
</tabel>

app/views/items/new.html.erb
<% provide(:title, "アイテム作成") %>
<%= form_for @item do |f| %>
 <% if @item.errors.any? %>
 <div id="error_explanation">
   <h2><%= pluralize(@item.errors.count, "error") %> エラーの為保存出来ません</h2>

   <ul>
   <% @item.errors.full_messages.each do |message| %>
     <li><%= message %></li>
   <% end %>
   </ul>
 </div>
 <% end %>

 <div class="form-group mt_50">
   <%= f.label :code %>
   <%= f.text_field :code,placeholder: "codeを入力して下さい", class: 'form-control' %>
 </div>

 <div class="form-group mt_50">
   <%= f.label :商品名 %>
   <%= f.text_field :name,placeholder: "商品名を入力して下さい", class: 'form-control' %>
 </div>

  <div class="form-group mt_50">
   <%= f.label :値段 %>
   <%= f.text_field :price,placeholder: "値段を入力して下さい", class: 'form-control' %>
 </div>

 <div class="form-group mt_50">
   <%= f.label :備考 %>
   <%= f.text_field :note,placeholder: "備考を入力して下さい", class: 'form-control' %>
 </div>

 <p><%= f.label :カテゴリー %></p>

<div>
 <%= f.collection_select(:category_id,Category.all,:id,:name,:prompt => true,class: "form-control")%>
</div>

<div class="form flex">
 <%= f.submit class: "btn btn-primary active" %>
</div>
 <% end %>

app/views/items/show.html.erb
<div class="show_container">
  <ul>
    <h2><%= @item.name %></h2>
    <li>ID:<%= @item.id %></li>
    <li>Code:<%= @item.code %></li>
    <li>Price:<%= @item.price %></li>
    <li>Category ID: <%= @item.category.id %></li>
    <li>Category Name: <%= @item.category.name %></li>
    <li>Item Note: <%= @item.note %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>prapp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <h1><%= yield(:title) %></h1>
    </div>
    <div class="sidebar">
      <ul>
        <li><h2><%= link_to 'カテゴリマスタ', root_path %></h2></li>
        <li><h2><%= link_to 'アイテムマスタ', items_path %></h2></li>
        <li><h2><%= link_to '注文マスタ', orders_path %></h2></li>
        <li><h2><%= link_to 'ユーザーマスタ', users_path %></h2></li>
      <ul>
    </div>
    <div class="main">
    <%= yield %>
    </div>
  </body>
</html>

app/views/orders/index.html.erb
<% provide(:title, "注文一覧") %>

app/views/users/index.html.erb
<% provide(:title, "ユーザー") %>
<div class="main-table-front">
      <%= link_to image_tag('btn_kensyu.png', class: 'btn_Add'), new_user_path %>
      <%= form_tag(users_path,:method => 'get' ,class: "serchform") do %>
   <%= text_field_tag :search,params[:search],:placeholder => "ユーザー入力" %>
 <%= submit_tag '検索', :name => nil ,class: "btn"%>
 <% end %>
</div>
<table border="1">
<thead>
<tr>
  <th>Code</th>
  <th class="category_th">ID</th>
  <th>name</th>
  <th>email</th>
  <th class="category_th">[x]</th>
</tr>
</thead>
<tbody>
<% @users.each do |user| %>
<tr>
  <td><%= user.code %></td>
  <td><%= user.id %></td>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= link_to '[x]',user_path(user),method: :delete,class: 'command',data: { confirm: 'Sure?' } %></td>
</tr>
<% end %>
</tbody>
</tabel>

app/views/users/new.html.erb
<% provide(:title, "アイテム作成") %>
<%= form_for @user do |f| %>
 <% if @user.errors.any? %>
 <div id="error_explanation">
   <h2><%= pluralize(@item.errors.count, "error") %> エラーの為保存出来ません</h2>

   <ul>
   <% @item.errors.full_messages.each do |message| %>
     <li><%= message %></li>
   <% end %>
   </ul>
 </div>
 <% end %>

<div class="form-group mt_50">
   <%= f.label :ユーザー名 %>
   <%= f.text_field :name,placeholder: "商品名を入力して下さい", class: 'form-control' %>
 </div>
 <div class="form-group mt_50">
   <%= f.label :code %>
   <%= f.text_field :code,placeholder: "codeを入力して下さい", class: 'form-control' %>
 </div>
  <div class="form-group mt_50">
   <%= f.label :email %>
   <%= f.text_field :email,placeholder: "アドレスを入力して下さい", class: 'form-control' %>
 </div>

<div class="form flex">
 <%= f.submit class: "btn btn-primary active" %>
</div>
 <% end %>